### ISSUE TITLE
Support for multiple dates.

### ISSUE THREAD

**Issue by pobocks** [alexduryee/timewalk#1]
Since Timetwister supports multiple dates pretty much seamlessly, it should be possible to support them in Timewalk.

Proposed method: take the array we're already getting back from timetwister, process the first one pretty much as done, and then process the subsequent ones, creating new dates with fixed values (resource_id, etc) taken from self, and variant values taken from the timetwister parse results.

**Comment by pobocks** [comment]
Hey, just a heads up - I'm seeing something weird going on - last date getting dropped in some (all?) cases when I do ingests via API. Best hold off on merging.

**Comment by pobocks** [comment]
Alright, I figured out what was happening - I was naively just processing resource_id, rather than the set of id fields that dates can associate with.  I'm looking for a list of those, or some other way of being exhaustive (I'm toying with the idea of finding a reflection method and just doing everything with /_id$/, since the dates are going to have the same values (coming from the same unitdate, as they are)

**Comment by pobocks** [comment]
So, I've got a prospective solution up - it's essentially based on reading the MySQL table.  I don't think a reflection-based solution would actually be a good idea, bc it feels like that would put us in danger of overly broad association of the dates? 

I've done basic testing, and this doesn't seem to drop dates on the floor, anyway?

**Comment by pobocks** [comment]
Also: is there any reasonable way to do automated tests for ASpace plugins?  I haven't found one yet.

**Comment by pobocks** [comment]
@alexduryee Prospective bulk fix up, testing now.

**Comment by pobocks** [comment]
Seems to work ok!

**Comment by alexduryee** [comment]
Thanks!  Added the `around_save` callback as discussed to maintain date ordering and merged in.
